[package]
name = "music"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.14.0"
crossterm = "0.20"
tui = { version = "0.16", default-features = false, features = ['crossterm'] }
